version: "3"

services:
  workspace:
    build:
      context: .
      args:
        - work_path=/workspace
        - work_user=vscode
    command: sleep infinity
    volumes:
      - ..:/workspace/phantasm:cached
